Beginning submitting parallel processes.
Base directory:                      Run3
Number of parallel executions:       2
Running input file:                  /home/michal/Desktop/RPIT/MAXIMA/analyticalResultsP.txt
Succesfully created directories for each execution and moved files inside.
Running script in Run3/dir1
Running script in Run3/dir2
Terminated
Terminated
All executions are complete. Now moving on to finish up.
Traceback (most recent call last):
  File "/home/michal/Desktop/RPIT/ASTRA/runParallel/MergeAndSort.py", line 38, in <module>
    df = pd.read_csv(loc + "/table.csv")
  File "/home/michal/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/michal/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/michal/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/michal/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/home/michal/.local/lib/python3.10/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/michal/Desktop/RPIT/ASTRA/runParallel/Run3/dir2/table.csv'
Data merged and saved to Run3. Leaving.
